### ISSUE TITLE
About contribution 

### ISSUE THREAD

**Issue by BinayakJha** [BinayakJha/Hacktoberfest-2022#2]
You can make 1 contribution to Portfolio Websites Folder

You can make 3 contribution to Programs Folder

For non coders there is another folder for them

**Comment by Arghya-Banerjee** [comment]
I want to add a project to the Programs Folder. Should I create a new issue for that or would you assign me it here only?

**Comment by BinayakJha** [comment]
Hello @Arghya-Banerjee you should first fork this repository and after this repo is forked then you can make a contribution to the forked repo and make a pull request

**Comment by Udyansingh** [comment]
I want to contribute

**Comment by BinayakJha** [comment]
Hello, @Udyansingh first fork the repo and then just add the files in the forked repo and send the pull request if it will meet the requirements of hacktoberfest then it will be merged and a Hacktoberfest accepted label will be added :)

**Comment by Pritam0077** [comment]
can i add my portfolio website?

**Comment by BinayakJha** [comment]
Yes @Pritam0077  you can add your portfolio website template in the Portfolio Website Template Folder :)

**Comment by Pritam0077** [comment]
added website
