### ISSUE TITLE
About forking and making a pull request

### ISSUE THREAD

**Issue by BinayakJha** [BinayakJha/Hacktoberfest-2022#33]
You can see this video for the tutorial of forking and making a pull request from this video :)
https://www.youtube.com/watch?v=nT8KGYVurIU

**Comment by Pritam0077** [comment]
what i have to do in this issue?

**Comment by BinayakJha** [comment]
You don't need to do anything about this issue. I have just added a link to a video tutorial of how to make a pull request for first time contributors :)
