### ISSUE TITLE
Repo got excluded :(

### ISSUE THREAD

**Issue by BinayakJha** [BinayakJha/Hacktoberfest-2022#46]

**Comment by vijay2249** [comment]
🥺🥺
What happened and why
Can we change that.

**Comment by BinayakJha** [comment]
I dont know i will try to make a new repo which and make sure that it does not get excluded :)

**Comment by vijay2249** [comment]
Can you paste the new repo link here please

**Comment by BinayakJha** [comment]
@vijay2249  I am trying to see what type of repo gets excluded and new repo will come soon

**Comment by BinayakJha** [comment]
New repo (only two PR per person) https://github.com/BinayakJha/Automation-Programs
